# Generated by Django 2.2.5 on 2019-09-20 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avater',
            field=models.ImageField(default='default.jpg', upload_to='avatars/'),
        ),
    ]
