# Generated by Django 2.2.5 on 2019-09-21 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190921_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
