# Generated by Django 2.2.5 on 2019-09-21 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='hobby',
        ),
        migrations.AlterField(
            model_name='user',
            name='avater',
            field=models.ImageField(default='default.jpg', upload_to='avatars/'),
        ),
    ]
